### ISSUE TITLE
How is occlusion determined?

### ISSUE THREAD

**Issue by gtangg12** [VincentHancoder/REPARO#3]
Hi, excellent work. In the paper you mention you are given occlusion O, but I am wondering how you obtain this.

**Comment by VincentHancoder** [comment]
Hi, bounding box and occlusion as input information **_B_** and **_O_** are based on the information obtained from existing a priori access. We recommend to automate the judgment of occlusion information in the image based on some existing image understanding work. Of course, you can specify the occlusion information by your own understanding of the image to facilitate the subsequent complementary processing.
